name: Artifacts & Job Outputs
on:
  workflow_dispatch: 
  push:
    branches:
      - main
      - dev
    paths-ignore: 
      - .github/workflows/*
jobs:
  Install:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.publish.output.file }}
    steps:
      - name: Checkout code
        uses: actions/Checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Publish JS file name
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'file={}' >> $GITHUB_OUTPUT ';'
      - name: Test code
        run: npm run test
      # - name: Lint test
      #   run: npm run lint
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
  Deploy:
    runs-on: ubuntu-latest
    needs: Install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
      - name: Download build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: List dist artifact
        run: ls
      - name: Published JS file name
        run: echo "${{ needs.Install.outputs.file }}"
      - name: Deploy code
        run: echo "Deploying..."
  # Build:
  #   runs-on: ubuntu-latest
  #   needs: Install
  #   steps:
  #     - name: Checkout code
  #       uses: actions/Checkout@v4
  #     - name: Install nodejs
  #       uses: actions/setup-node@v3
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Lint test
  #       run: npm run lint 
  #     - name: Build code
  #       run: npm run build