name: Artifacts & Job Outputs
on:
  workflow_dispatch: 
  push:
    branches:
      - main
      - dev
    paths-ignore: 
      - .github/workflows/*
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/Checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Test code
        run: npm run test
      - name: Lint test
        run: npm run lint
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
  # Build:
  #   runs-on: ubuntu-latest
  #   needs: Install
  #   steps:
  #     - name: Checkout code
  #       uses: actions/Checkout@v4
  #     - name: Install nodejs
  #       uses: actions/setup-node@v3
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Lint test
  #       run: npm run lint 
  #     - name: Build code
  #       run: npm run build