name: Events
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo " ${{ toJson(github.event) }}"
      - name: Checkout code
        run: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm test
      - name: Build code
        run: npm build
      - name: Deploy code
        run: echo "Deploying code"