name: Reactjs App CI pipeline
on: push
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: npm install
        run: npm install