name: Reactjs App CI pipeline
on: push
jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  Deploy:
    runs-on: ubuntu-latest
    needs: Install
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build